# Render deployment configuration for games site
services:
  - type: web
    name: misbah-games
    env: static
    buildCommand: cd games && npm install && npm run build
    staticPublishPath: ./games/build
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html