# Render deployment configuration for terminal site
services:
  - type: web
    name: misbah-terminal
    env: static
    buildCommand: ""
    staticPublishPath: ./terminal
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html